# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b110eb03e89654b8b24b23ba185fe8ab8f1bff77d7c8d6f4c9a056b84c96ab062c9dc922ad92e06077b6871c3150eea4aa6ab89c17d5fdd60ab8dc2f161f5c82

test:
  secret_key_base: 9c56055589e61668178671c6f2ac06f691da8973845464dc7592283569ef0e8828007a7402b17414d2c5f2a58f1d79b3bb2dae96fa65b3bb80b35d5a663e6db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
